# -*- coding: utf-8 -*-
"""weather_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lRrQKSRrUlE_DdE7esjt0SncugL9FEWC
"""

import requests
ulr = 'https://opendata.cwa.gov.tw/api/v1/rest/datastore/F-C0032-001?Authorization=CWA-EE0FA5AF-16E7-4E77-80A0-97172349E1A5'

data = requests.get(ulr).json()
data['records']['location'][5]['weatherElement'][2]